const ERROR = {
  ERROR_LOGIC: 400,
  UNAUTHEN_ERROR: 403,
  HANDLE_ERROR: 402,
  GENERAL_ERROR: 500,
  OFFLINE_ERROR: 502,
  NO_ERROR: 200,
  NOTFOUND_ERROR: 404,
};
const MESSAGE = {
  SUCCESSFULL: 'SUCCESSFULL',
  FAIL: 'FAIL',
};
module.exports = {
  ERROR,
  MESSAGE,
};
